---
# defaults file for gitlab
gitlab_domain: gitlab.bolgovsky.ru
gitlab_external_url: "http://{{ gitlab_domain }}/"
gitlab_edition: "gitlab-ce"
gitlab_config_template: "gitlab.rb.j2"
gitlab_repository_installation_script_url: "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.deb.sh"

# Dependencies.
gitlab_dependencies:
  - postfix
  - curl
  - tzdata

# Optional settings.
gitlab_time_zone: "UTC"
gitlab_default_theme: '2'

# GitLab root password after install
gitlab_root_pass: "G1tl@bP@$$w0rd"

# GitLab runner token after install
gitlab_runner_token: "45817210-36f6-4093-8df5-f76b60481a09"